version: '2.1'
orbs:
  cypress: cypress-io/cypress@3
workflows:
  use-my-orb:
    jobs:
      - cypress/run:
        start-command: npm run start
          cypress-command: npx cypress run --parallel --record
          parallelism: 2