version: 2.1
orbs:
  cypress: cypress-io/cypress@2.2.0
workflows:
  build:
    jobs:
        - cypress/install
        - cypress/run:
            requires: 
              - cypress/install
          cypress-command: npx cypress run --record
            store_artifacts: true
            spec: cypress/e2e/login.cy.js
        - cypress/run:
            requires: 
              - cypress/install
            store_artifacts: true
            spec: cypress/e2e/basket.cy.js
        - cypress/run:
            requires: 
              - cypress/install
            store_artifacts: true
            spec: cypress/e2e/order.cy.js
        - cypress/run:
            requires: 
              - cypress/install
            store_artifacts: true
            spec: cypress/e2e/shoptest.cy.js
            parallel: true
            parallelism: 2 